/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package debtcontrol.form;

import debtcontrol.model.JedinicaMere;
import debtcontrol.model.Proizvod;
import debtcontrol.repository.ProizvodInterface;
import debtcontrol.repositoryImpl.ProizvodInterfaceImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author podrska
 */
public class DodajProizvodForm extends javax.swing.JDialog {

    ProizvodInterface proizvodInterface;

    /**
     * Creates new form DodajProizvodForm
     */
    public DodajProizvodForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        proizvodInterface = new ProizvodInterfaceImpl();

        initComponents();
        setLocationRelativeTo(null);

        popuniCombo();
        txtKolicina.setText(String.valueOf(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlUnesiteNoviProizvod = new javax.swing.JPanel();
        txtKolicina = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNazivProizvoda = new javax.swing.JLabel();
        lblCena = new javax.swing.JLabel();
        lblJedinicaMere = new javax.swing.JLabel();
        lblKolicina = new javax.swing.JLabel();
        txtNazivProizvoda = new javax.swing.JTextField();
        txtCenaProizvoda = new javax.swing.JTextField();
        comboBoxJedinicaMere = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DODAJ NOVI PROIZVOD");
        setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pnlUnesiteNoviProizvod.setBackground(new java.awt.Color(204, 255, 204));
        pnlUnesiteNoviProizvod.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtKolicina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKolicina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUnesiteNoviProizvod.add(txtKolicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 212, -1));

        btnSacuvaj.setBackground(new java.awt.Color(153, 204, 255));
        btnSacuvaj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSacuvaj.setText("SAČUVAJ");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });
        pnlUnesiteNoviProizvod.add(btnSacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 130, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("UNESITE NOVI PROIZVOD");
        pnlUnesiteNoviProizvod.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 250, 44));

        lblNazivProizvoda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNazivProizvoda.setText("NAZIV PROIZVODA");
        pnlUnesiteNoviProizvod.add(lblNazivProizvoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        lblCena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCena.setText("CENA PROIZVODA");
        pnlUnesiteNoviProizvod.add(lblCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 170, -1));

        lblJedinicaMere.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJedinicaMere.setText("JEDINICA MERE");
        pnlUnesiteNoviProizvod.add(lblJedinicaMere, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 143, -1));

        lblKolicina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKolicina.setText("KOLIČINA");
        pnlUnesiteNoviProizvod.add(lblKolicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 143, -1));

        txtNazivProizvoda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNazivProizvoda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUnesiteNoviProizvod.add(txtNazivProizvoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 212, -1));

        txtCenaProizvoda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCenaProizvoda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUnesiteNoviProizvod.add(txtCenaProizvoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 212, -1));

        comboBoxJedinicaMere.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboBoxJedinicaMere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUnesiteNoviProizvod.add(comboBoxJedinicaMere, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 210, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        pnlUnesiteNoviProizvod.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 690, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(pnlUnesiteNoviProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(pnlUnesiteNoviProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        if (txtNazivProizvoda.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "NIste uneli naziv proizvoda na adekvatan način ");
            return;
        }

        if (txtCenaProizvoda.getText().isEmpty() || !txtCenaProizvoda.getText().matches("[0-9]*\\.?[0-9]+")) {
            JOptionPane.showMessageDialog(null, "NIste uneli cenu na odgovarajuci način");
            return;
        }

        if (txtKolicina.getText().isEmpty() || !txtKolicina.getText().matches("[0-9]*\\.?[0-9]+")) {
            JOptionPane.showMessageDialog(null, "NIste uneli količinu na odgovarajući način");
            return;
        }

        Proizvod p = new Proizvod(0, txtNazivProizvoda.getText().trim(), Double.parseDouble(txtCenaProizvoda.getText().trim()), comboBoxJedinicaMere.getSelectedItem().toString(), Double.parseDouble(txtKolicina.getText().trim()), null);
        try {
            proizvodInterface.dodajNoviProizvod(p);
            System.out.println("Unet je proizvod u bazu");
            dispose();
        } catch (Exception e) {
            System.out.println("Nije sacuvan proizvod " + e.getMessage());
        }
        dispose();
    }//GEN-LAST:event_btnSacuvajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> comboBoxJedinicaMere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblJedinicaMere;
    private javax.swing.JLabel lblKolicina;
    private javax.swing.JLabel lblNazivProizvoda;
    private javax.swing.JPanel pnlUnesiteNoviProizvod;
    private javax.swing.JTextField txtCenaProizvoda;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtNazivProizvoda;
    // End of variables declaration//GEN-END:variables

    private void popuniCombo() {

        for (JedinicaMere jedMere : JedinicaMere.values()) {
            comboBoxJedinicaMere.addItem(jedMere.toString());
        }
    }

}
