/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package debtcontrol.form;

import debtcontrol.form.controller.DodajKorisnikaController;
import debtcontrol.model.Korisnik;
import debtcontrol.model.Proizvod;
import debtcontrol.repository.KorisnikInterface;
import debtcontrol.repositoryImpl.KorisnikInterfaceImpl;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author podrska
 */
public class DodajKorisnikaForm extends javax.swing.JDialog {

    KorisnikInterface korisnikInterface;

   
    public DodajKorisnikaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        korisnikInterface = new KorisnikInterfaceImpl();
        initComponents();
        setLocationRelativeTo(null);
        lblerrormailObavestavanje.setVisible(false);
        lblErroIme.setVisible(false);
        lblerrorPrezime.setVisible(false);
        lblerrorMail.setVisible(false);
        lblerrormailObavestavanje.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        pnlUnesiNovogkorisnika = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        btnSacuvajKorisnika = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        radioBtnPrihvata = new javax.swing.JRadioButton();
        radioBtnNePrihvata = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblErroIme = new javax.swing.JLabel();
        lblerrorPrezime = new javax.swing.JLabel();
        lblerrorMail = new javax.swing.JLabel();
        lblerrormailObavestavanje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UNESITE  NOVOG  KORISNIKA ");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pnlUnesiNovogkorisnika.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("UNESITE NOVOG KORISNIKA");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("IME ");

        txtIme.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImeKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("PREZIME");

        txtPrezime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrezime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrezime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrezimeKeyTyped(evt);
            }
        });

        btnSacuvajKorisnika.setBackground(new java.awt.Color(153, 204, 255));
        btnSacuvajKorisnika.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSacuvajKorisnika.setText("SACUVAJ");
        btnSacuvajKorisnika.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSacuvajKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajKorisnikaActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setText("E MAIL");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("E-MAIL OBAVEŠTAVANJE");

        radioBtnPrihvata.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(radioBtnPrihvata);
        radioBtnPrihvata.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioBtnPrihvata.setText("PRIHVATA");

        radioBtnNePrihvata.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(radioBtnNePrihvata);
        radioBtnNePrihvata.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioBtnNePrihvata.setText("NE PRIHVATA");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblErroIme.setForeground(new java.awt.Color(255, 0, 0));
        lblErroIme.setText("jLabel1");

        lblerrorPrezime.setForeground(new java.awt.Color(255, 0, 0));
        lblerrorPrezime.setText("jLabel2");

        lblerrorMail.setForeground(new java.awt.Color(255, 0, 51));
        lblerrorMail.setText("jLabel3");

        lblerrormailObavestavanje.setForeground(new java.awt.Color(255, 0, 0));
        lblerrormailObavestavanje.setText("jLabel4");

        javax.swing.GroupLayout pnlUnesiNovogkorisnikaLayout = new javax.swing.GroupLayout(pnlUnesiNovogkorisnika);
        pnlUnesiNovogkorisnika.setLayout(pnlUnesiNovogkorisnikaLayout);
        pnlUnesiNovogkorisnikaLayout.setHorizontalGroup(
            pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnesiNovogkorisnikaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addGap(52, 52, 52)
                .addComponent(radioBtnPrihvata)
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(pnlUnesiNovogkorisnikaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUnesiNovogkorisnikaLayout.createSequentialGroup()
                .addGroup(pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUnesiNovogkorisnikaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvajKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUnesiNovogkorisnikaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioBtnNePrihvata))
                    .addGroup(pnlUnesiNovogkorisnikaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblerrormailObavestavanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblerrorMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblerrorPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErroIme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(txtIme)
                            .addComponent(txtEmail))))
                .addGap(140, 140, 140))
            .addGroup(pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUnesiNovogkorisnikaLayout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(246, Short.MAX_VALUE)))
        );
        pnlUnesiNovogkorisnikaLayout.setVerticalGroup(
            pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnesiNovogkorisnikaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblErroIme)
                .addGap(17, 17, 17)
                .addGroup(pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblerrorPrezime)
                .addGap(18, 18, 18)
                .addGroup(pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblerrorMail)
                .addGap(18, 18, 18)
                .addGroup(pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblerrormailObavestavanje)
                .addGroup(pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(radioBtnPrihvata)
                    .addComponent(radioBtnNePrihvata))
                .addGap(59, 59, 59)
                .addComponent(btnSacuvajKorisnika)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(pnlUnesiNovogkorisnikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUnesiNovogkorisnikaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addContainerGap(394, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUnesiNovogkorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUnesiNovogkorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajKorisnikaActionPerformed

//        if (txtIme.getText().isEmpty()) {
//    
//            lblErroIme.setVisible(true);
//            lblErroIme.setText("NISTE UNELI IME ");
//            return;
//
//        }
//
//        if (txtPrezime.getText().isEmpty()) {
//           
//            lblerrorPrezime.setVisible(true);
//            lblerrorPrezime.setText("NISTE UNELI PREZIME ");
//
//            return;
//        }
//
//        if (txtEmail.getText().isEmpty()) {
//           
//            lblerrorMail.setVisible(true);
//            lblerrorMail.setText("NISTE UNELI E-MAIL NA ODGOVARAJUĆI NAČIN");
//
//            return;
//        }
//
//
//        if (!radioBtnNePrihvata.isSelected() && !radioBtnPrihvata.isSelected()) {
//
//            JOptionPane.showMessageDialog(null, "NISTE SELEKTOVALI  E-MAIL OBAVEŠTENJE");
//
//            lblerrormailObavestavanje.setVisible(true);
//            lblerrormailObavestavanje.setText("NISTE SELEKTOVALI  E-MAIL OBAVEŠTENJE");
//            return;
//
//        }
//        boolean prihvata = radioBtnPrihvata.isSelected();
//        boolean nePrihvata = radioBtnNePrihvata.isSelected();
//
//        if (prihvata) {
//
//            Korisnik korisnik = new Korisnik(0, txtIme.getText().trim(), txtPrezime.getText().trim(), txtEmail.getText().trim(), true);
//            korisnikInterface.dodajKorisnika(korisnik);
//
//            System.out.println("Korisnik je " + korisnik);
//
//        } else if (nePrihvata) {
//            Korisnik korisnik = new Korisnik(0, txtIme.getText().trim(), txtPrezime.getText().trim(), txtEmail.getText().trim(), false);
//            korisnikInterface.dodajKorisnika(korisnik);
//
//            System.out.println("Korisnik je " + korisnik);
//        }

            DodajKorisnikaController.sacuvajKorisnika(txtIme, txtPrezime, txtEmail, radioBtnPrihvata, radioBtnNePrihvata, lblErroIme, lblerrorPrezime, lblerrorMail, lblerrormailObavestavanje, this);

       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacuvajKorisnikaActionPerformed

    private void txtImeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
            evt.consume();
            lblErroIme.setVisible(true);
            lblErroIme.setText("NISTE UNELI IME NA ODGOVARAJUCI NAČIN");
        } else {
            lblErroIme.setVisible(true);
            lblErroIme.setText("");
        }

    }//GEN-LAST:event_txtImeKeyTyped

    private void txtPrezimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrezimeKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
            evt.consume();
            lblerrorPrezime.setVisible(true);
            lblerrorPrezime.setText("NISTE UNELI PREZIME NA ODGOVARAJUCI NAČIN");

        } else {
            lblerrorPrezime.setVisible(true);
            lblerrorPrezime.setText("");
        }
    }//GEN-LAST:event_txtPrezimeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajKorisnika;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErroIme;
    private javax.swing.JLabel lblerrorMail;
    private javax.swing.JLabel lblerrorPrezime;
    private javax.swing.JLabel lblerrormailObavestavanje;
    private javax.swing.JPanel pnlUnesiNovogkorisnika;
    private javax.swing.JRadioButton radioBtnNePrihvata;
    private javax.swing.JRadioButton radioBtnPrihvata;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
