/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package debtcontrol.form;

import debtcontrol.form.controller.IzvestajProizvodaController;
import debtcontrol.model.Proizvod;
import debtcontrol.repository.ProizvodInterface;
import debtcontrol.repositoryImpl.ProizvodInterfaceImpl;

/**
 *
 * @author podrska
 */
public class IzvestajProizvodaForm extends javax.swing.JDialog {
    
    ProizvodInterface proizvodInterface;
    Proizvod proizvod;

    /**
     * Creates new form IzvestajProizvodaForm
     */
    public IzvestajProizvodaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        proizvodInterface = new ProizvodInterfaceImpl();
        pnlPodaciOProizvodu.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlSviProizvodi = new javax.swing.JPanel();
        btnKafa = new javax.swing.JButton();
        btnKafaSaMlekom = new javax.swing.JButton();
        btnKapucino = new javax.swing.JButton();
        btnEspresoSaMlekom = new javax.swing.JButton();
        btnMleko = new javax.swing.JButton();
        btnToplaCokolada = new javax.swing.JButton();
        btnKiselaVoda = new javax.swing.JButton();
        btnSokBorovnica = new javax.swing.JButton();
        btnEspresso = new javax.swing.JButton();
        btnKafaKabeza = new javax.swing.JButton();
        btnNeskafa = new javax.swing.JButton();
        btnCajKamilica = new javax.swing.JButton();
        btnMed = new javax.swing.JButton();
        btnRosa = new javax.swing.JButton();
        btnSokNarandza = new javax.swing.JButton();
        btnCajHibiskus = new javax.swing.JButton();
        btnCajNana = new javax.swing.JButton();
        btnCajZeleni = new javax.swing.JButton();
        btnCajJabukaCimet = new javax.swing.JButton();
        btnCajDjumbir = new javax.swing.JButton();
        btnCedjenaPomorandza = new javax.swing.JButton();
        btnCedjeniGrejpfrut = new javax.swing.JButton();
        btnCedjeniMiks = new javax.swing.JButton();
        btnLimunada = new javax.swing.JButton();
        btnSvepsBiterLemon = new javax.swing.JButton();
        btnKokaKola = new javax.swing.JButton();
        btnSvepsTangerina = new javax.swing.JButton();
        pnlPodaciOProizvodu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStanje = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IZVEŠTAJ PROIZVODA");

        pnlSviProizvodi.setBackground(new java.awt.Color(255, 255, 255));

        btnKafa.setBackground(new java.awt.Color(204, 153, 0));
        btnKafa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnKafa.setText("KAFA");
        btnKafa.setBorder(new javax.swing.border.MatteBorder(null));
        btnKafa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKafaActionPerformed(evt);
            }
        });

        btnKafaSaMlekom.setBackground(new java.awt.Color(204, 153, 0));
        btnKafaSaMlekom.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnKafaSaMlekom.setText("<html>KAFA <br>SA MLEKOM</html>");
        btnKafaSaMlekom.setBorder(new javax.swing.border.MatteBorder(null));
        btnKafaSaMlekom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKafaSaMlekomActionPerformed(evt);
            }
        });

        btnKapucino.setBackground(new java.awt.Color(204, 153, 0));
        btnKapucino.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnKapucino.setText("KAPUĆINO");
        btnKapucino.setBorder(new javax.swing.border.MatteBorder(null));
        btnKapucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKapucinoActionPerformed(evt);
            }
        });

        btnEspresoSaMlekom.setBackground(new java.awt.Color(204, 153, 0));
        btnEspresoSaMlekom.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEspresoSaMlekom.setText("<html>ESPRESO <br>SA MLEKOM</html>");
        btnEspresoSaMlekom.setBorder(new javax.swing.border.MatteBorder(null));
        btnEspresoSaMlekom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspresoSaMlekomActionPerformed(evt);
            }
        });

        btnMleko.setBackground(new java.awt.Color(204, 153, 0));
        btnMleko.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnMleko.setText("MLEKO");
        btnMleko.setBorder(new javax.swing.border.MatteBorder(null));
        btnMleko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMlekoActionPerformed(evt);
            }
        });

        btnToplaCokolada.setBackground(new java.awt.Color(204, 153, 0));
        btnToplaCokolada.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnToplaCokolada.setText("<html>TOPLA <br>ČOKOLADA</html>");
        btnToplaCokolada.setBorder(new javax.swing.border.MatteBorder(null));
        btnToplaCokolada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplaCokoladaActionPerformed(evt);
            }
        });

        btnKiselaVoda.setBackground(new java.awt.Color(204, 153, 0));
        btnKiselaVoda.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnKiselaVoda.setText("<html>KISELA <br>VODA</html>");
        btnKiselaVoda.setBorder(new javax.swing.border.MatteBorder(null));
        btnKiselaVoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiselaVodaActionPerformed(evt);
            }
        });

        btnSokBorovnica.setBackground(new java.awt.Color(204, 153, 0));
        btnSokBorovnica.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSokBorovnica.setText("<html>SOK <br>BOROVNICA</html>");
        btnSokBorovnica.setBorder(new javax.swing.border.MatteBorder(null));
        btnSokBorovnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokBorovnicaActionPerformed(evt);
            }
        });

        btnEspresso.setBackground(new java.awt.Color(204, 153, 0));
        btnEspresso.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEspresso.setText("ESPRESO");
        btnEspresso.setBorder(new javax.swing.border.MatteBorder(null));
        btnEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspressoActionPerformed(evt);
            }
        });

        btnKafaKabeza.setBackground(new java.awt.Color(204, 153, 0));
        btnKafaKabeza.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnKafaKabeza.setText("<html>   KAFA <br>KABEZA</html>\n");
        btnKafaKabeza.setBorder(new javax.swing.border.MatteBorder(null));
        btnKafaKabeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKafaKabezaActionPerformed(evt);
            }
        });

        btnNeskafa.setBackground(new java.awt.Color(204, 153, 0));
        btnNeskafa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnNeskafa.setText("NES KAFA");
        btnNeskafa.setBorder(new javax.swing.border.MatteBorder(null));
        btnNeskafa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeskafaActionPerformed(evt);
            }
        });

        btnCajKamilica.setBackground(new java.awt.Color(0, 204, 153));
        btnCajKamilica.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCajKamilica.setText("<html>ČAJ <br>KAMILICA</html>");
        btnCajKamilica.setBorder(new javax.swing.border.MatteBorder(null));
        btnCajKamilica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajKamilicaActionPerformed(evt);
            }
        });

        btnMed.setBackground(new java.awt.Color(204, 153, 0));
        btnMed.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnMed.setText("MED");
        btnMed.setBorder(new javax.swing.border.MatteBorder(null));
        btnMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedActionPerformed(evt);
            }
        });

        btnRosa.setBackground(new java.awt.Color(204, 153, 0));
        btnRosa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRosa.setText("ROSA");
        btnRosa.setBorder(new javax.swing.border.MatteBorder(null));
        btnRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRosaActionPerformed(evt);
            }
        });

        btnSokNarandza.setBackground(new java.awt.Color(204, 153, 0));
        btnSokNarandza.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSokNarandza.setText("<html>SOK <br>NARANDŽA</html>");
        btnSokNarandza.setBorder(new javax.swing.border.MatteBorder(null));
        btnSokNarandza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokNarandzaActionPerformed(evt);
            }
        });

        btnCajHibiskus.setBackground(new java.awt.Color(0, 204, 153));
        btnCajHibiskus.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCajHibiskus.setText("<html>ČAJ <br>HIBISKUS</html>");
        btnCajHibiskus.setBorder(new javax.swing.border.MatteBorder(null));
        btnCajHibiskus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajHibiskusActionPerformed(evt);
            }
        });

        btnCajNana.setBackground(new java.awt.Color(0, 204, 153));
        btnCajNana.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCajNana.setText("<html>ČAJ <br>NANA</html>");
        btnCajNana.setBorder(new javax.swing.border.MatteBorder(null));
        btnCajNana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajNanaActionPerformed(evt);
            }
        });

        btnCajZeleni.setBackground(new java.awt.Color(0, 204, 153));
        btnCajZeleni.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCajZeleni.setText("<html>ČAJ <br>ZELENI</html>");
        btnCajZeleni.setBorder(new javax.swing.border.MatteBorder(null));
        btnCajZeleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajZeleniActionPerformed(evt);
            }
        });

        btnCajJabukaCimet.setBackground(new java.awt.Color(0, 204, 153));
        btnCajJabukaCimet.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCajJabukaCimet.setText("<html>ČAJ <br>JABUKA-CIMET</html>");
        btnCajJabukaCimet.setBorder(new javax.swing.border.MatteBorder(null));
        btnCajJabukaCimet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajJabukaCimetActionPerformed(evt);
            }
        });

        btnCajDjumbir.setBackground(new java.awt.Color(0, 204, 153));
        btnCajDjumbir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCajDjumbir.setText("<html>ČAJ <br>DJUMBIR</html>");
        btnCajDjumbir.setBorder(new javax.swing.border.MatteBorder(null));
        btnCajDjumbir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajDjumbirActionPerformed(evt);
            }
        });

        btnCedjenaPomorandza.setBackground(new java.awt.Color(0, 204, 153));
        btnCedjenaPomorandza.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCedjenaPomorandza.setText("<html>CEDJENA <br>POMORANDŽA</html>");
        btnCedjenaPomorandza.setBorder(new javax.swing.border.MatteBorder(null));
        btnCedjenaPomorandza.setMargin(new java.awt.Insets(2, 8, 3, 14));
        btnCedjenaPomorandza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCedjenaPomorandzaActionPerformed(evt);
            }
        });

        btnCedjeniGrejpfrut.setBackground(new java.awt.Color(0, 204, 153));
        btnCedjeniGrejpfrut.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCedjeniGrejpfrut.setText("<html>CEDJENI <br>GREJPFRUT</html>");
        btnCedjeniGrejpfrut.setBorder(new javax.swing.border.MatteBorder(null));
        btnCedjeniGrejpfrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCedjeniGrejpfrutActionPerformed(evt);
            }
        });

        btnCedjeniMiks.setBackground(new java.awt.Color(0, 204, 153));
        btnCedjeniMiks.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCedjeniMiks.setText("<html>CEDJENI <br>MIKS</html>");
        btnCedjeniMiks.setBorder(new javax.swing.border.MatteBorder(null));
        btnCedjeniMiks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCedjeniMiksActionPerformed(evt);
            }
        });

        btnLimunada.setBackground(new java.awt.Color(0, 204, 153));
        btnLimunada.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimunada.setText("LIMUNADA");
        btnLimunada.setBorder(new javax.swing.border.MatteBorder(null));
        btnLimunada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimunadaActionPerformed(evt);
            }
        });

        btnSvepsBiterLemon.setBackground(new java.awt.Color(0, 204, 153));
        btnSvepsBiterLemon.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSvepsBiterLemon.setText("<html>ŠVEPS <br>BITERLEMON</html>");
        btnSvepsBiterLemon.setBorder(new javax.swing.border.MatteBorder(null));
        btnSvepsBiterLemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSvepsBiterLemonActionPerformed(evt);
            }
        });

        btnKokaKola.setBackground(new java.awt.Color(0, 204, 153));
        btnKokaKola.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnKokaKola.setText("KOKA KOLA");
        btnKokaKola.setBorder(new javax.swing.border.MatteBorder(null));
        btnKokaKola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKokaKolaActionPerformed(evt);
            }
        });

        btnSvepsTangerina.setBackground(new java.awt.Color(0, 204, 153));
        btnSvepsTangerina.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSvepsTangerina.setText("<html>ŠVEPS <br>TANGERINA</html>");
        btnSvepsTangerina.setBorder(new javax.swing.border.MatteBorder(null));
        btnSvepsTangerina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSvepsTangerinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSviProizvodiLayout = new javax.swing.GroupLayout(pnlSviProizvodi);
        pnlSviProizvodi.setLayout(pnlSviProizvodiLayout);
        pnlSviProizvodiLayout.setHorizontalGroup(
            pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSviProizvodiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlSviProizvodiLayout.createSequentialGroup()
                            .addComponent(btnKafa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnMleko, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnCajNana, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnCedjenaPomorandza, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnSvepsBiterLemon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlSviProizvodiLayout.createSequentialGroup()
                            .addComponent(btnKafaSaMlekom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnToplaCokolada, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnKafaKabeza, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnRosa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnCajZeleni, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnCedjeniGrejpfrut, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnKokaKola, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlSviProizvodiLayout.createSequentialGroup()
                            .addComponent(btnKapucino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnKiselaVoda, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnNeskafa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnSokNarandza, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnCajJabukaCimet, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnCedjeniMiks, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnSvepsTangerina, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlSviProizvodiLayout.createSequentialGroup()
                            .addComponent(btnEspresoSaMlekom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnSokBorovnica, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnCajKamilica, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnCajHibiskus, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnCajDjumbir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnLimunada, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlSviProizvodiLayout.setVerticalGroup(
            pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
            .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSviProizvodiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnKafa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMleko, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMed, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCedjenaPomorandza, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlSviProizvodiLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCajNana, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSvepsBiterLemon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(18, 18, 18)
                    .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnKafaSaMlekom, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCajZeleni, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCedjeniGrejpfrut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlSviProizvodiLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnToplaCokolada, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnKafaKabeza, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRosa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnKokaKola, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(18, 18, 18)
                    .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnKapucino, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnKiselaVoda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNeskafa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSokNarandza, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCajJabukaCimet, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlSviProizvodiLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCedjeniMiks, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSvepsTangerina, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(17, 17, 17)
                    .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEspresoSaMlekom, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSokBorovnica, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCajKamilica, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCajHibiskus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlSviProizvodiLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(pnlSviProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCajDjumbir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLimunada, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlPodaciOProizvodu.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("PROIZVOD");

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNaziv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNaziv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("CENA");

        txtCena.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("STANJE (kom)");

        txtStanje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtStanje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("UKUPNO (din)");

        txtUkupno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUkupno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlPodaciOProizvoduLayout = new javax.swing.GroupLayout(pnlPodaciOProizvodu);
        pnlPodaciOProizvodu.setLayout(pnlPodaciOProizvoduLayout);
        pnlPodaciOProizvoduLayout.setHorizontalGroup(
            pnlPodaciOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodaciOProizvoduLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPodaciOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPodaciOProizvoduLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addGroup(pnlPodaciOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(pnlPodaciOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlPodaciOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStanje)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(pnlPodaciOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUkupno)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        pnlPodaciOProizvoduLayout.setVerticalGroup(
            pnlPodaciOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodaciOProizvoduLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlPodaciOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnlPodaciOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSviProizvodi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPodaciOProizvodu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSviProizvodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlPodaciOProizvodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKafaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKafaActionPerformed

//        proizvod = proizvodInterface.pronadjiProizvod(1);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//        txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);

            IzvestajProizvodaController.izvestajProizvoda(1, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnKafaActionPerformed

    private void btnKafaSaMlekomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKafaSaMlekomActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(2);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//        txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
        
         IzvestajProizvodaController.izvestajProizvoda(2, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnKafaSaMlekomActionPerformed

    private void btnKapucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKapucinoActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(3);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//        txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
        
        
         IzvestajProizvodaController.izvestajProizvoda(3, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnKapucinoActionPerformed

    private void btnEspresoSaMlekomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspresoSaMlekomActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(4);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(4, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnEspresoSaMlekomActionPerformed

    private void btnMlekoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMlekoActionPerformed

//        proizvod = proizvodInterface.pronadjiProizvod(8);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(8, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);

      
    }//GEN-LAST:event_btnMlekoActionPerformed

    private void btnToplaCokoladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToplaCokoladaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(9);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(9, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnToplaCokoladaActionPerformed

    private void btnKiselaVodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiselaVodaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(12);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena())); 
//        txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(12, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnKiselaVodaActionPerformed

    private void btnSokBorovnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokBorovnicaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(15);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(15, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnSokBorovnicaActionPerformed

    private void btnEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspressoActionPerformed

//        proizvod = proizvodInterface.pronadjiProizvod(7);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(7, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnEspressoActionPerformed

    private void btnKafaKabezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKafaKabezaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(13);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(13, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnKafaKabezaActionPerformed

    private void btnNeskafaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeskafaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(5);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(5, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnNeskafaActionPerformed

    private void btnCajKamilicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajKamilicaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(23);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(23, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnCajKamilicaActionPerformed

    private void btnMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(6);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(6, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnMedActionPerformed

    private void btnRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRosaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(10);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
//        
         IzvestajProizvodaController.izvestajProizvoda(10, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnRosaActionPerformed

    private void btnSokNarandzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokNarandzaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(14);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
//        
         IzvestajProizvodaController.izvestajProizvoda(14, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnSokNarandzaActionPerformed

    private void btnCajHibiskusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajHibiskusActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(24);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(24, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnCajHibiskusActionPerformed

    private void btnCajNanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajNanaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(19);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
//        
         IzvestajProizvodaController.izvestajProizvoda(19, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnCajNanaActionPerformed

    private void btnCajZeleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajZeleniActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(20);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(20, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnCajZeleniActionPerformed

    private void btnCajJabukaCimetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajJabukaCimetActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(21);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
//        
         IzvestajProizvodaController.izvestajProizvoda(21, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnCajJabukaCimetActionPerformed

    private void btnCajDjumbirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajDjumbirActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(22);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
//        
         IzvestajProizvodaController.izvestajProizvoda(22, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnCajDjumbirActionPerformed

    private void btnCedjenaPomorandzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCedjenaPomorandzaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(25);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(25, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnCedjenaPomorandzaActionPerformed

    private void btnCedjeniGrejpfrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCedjeniGrejpfrutActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(26);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(26, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnCedjeniGrejpfrutActionPerformed

    private void btnCedjeniMiksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCedjeniMiksActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(27);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(27, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnCedjeniMiksActionPerformed

    private void btnLimunadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimunadaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(28);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(28, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnLimunadaActionPerformed

    private void btnSvepsBiterLemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSvepsBiterLemonActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(30);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(30, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnSvepsBiterLemonActionPerformed

    private void btnKokaKolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKokaKolaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(29);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(29, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnKokaKolaActionPerformed

    private void btnSvepsTangerinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSvepsTangerinaActionPerformed
//        proizvod = proizvodInterface.pronadjiProizvod(31);
//
//        txtNaziv.setText(proizvod.getNaziv());
//        txtCena.setText(String.valueOf(proizvod.getCena()));
//         txtStanje.setText(String.valueOf(proizvod.getKolicina()));
//        txtUkupno.setText(String.valueOf(proizvod.getKolicina() * proizvod.getCena()));
//        txtId.setText(String.valueOf(proizvod.getIdProizvoda()));
//        pnlPodaciOProizvodu.setVisible(true);
        
         IzvestajProizvodaController.izvestajProizvoda(31, proizvod, txtNaziv, txtCena, txtStanje, txtUkupno, txtId, pnlPodaciOProizvodu);
    }//GEN-LAST:event_btnSvepsTangerinaActionPerformed

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCajDjumbir;
    private javax.swing.JButton btnCajHibiskus;
    private javax.swing.JButton btnCajJabukaCimet;
    private javax.swing.JButton btnCajKamilica;
    private javax.swing.JButton btnCajNana;
    private javax.swing.JButton btnCajZeleni;
    private javax.swing.JButton btnCedjenaPomorandza;
    private javax.swing.JButton btnCedjeniGrejpfrut;
    private javax.swing.JButton btnCedjeniMiks;
    private javax.swing.JButton btnEspresoSaMlekom;
    private javax.swing.JButton btnEspresso;
    private javax.swing.JButton btnKafa;
    private javax.swing.JButton btnKafaKabeza;
    private javax.swing.JButton btnKafaSaMlekom;
    private javax.swing.JButton btnKapucino;
    private javax.swing.JButton btnKiselaVoda;
    private javax.swing.JButton btnKokaKola;
    private javax.swing.JButton btnLimunada;
    private javax.swing.JButton btnMed;
    private javax.swing.JButton btnMleko;
    private javax.swing.JButton btnNeskafa;
    private javax.swing.JButton btnRosa;
    private javax.swing.JButton btnSokBorovnica;
    private javax.swing.JButton btnSokNarandza;
    private javax.swing.JButton btnSvepsBiterLemon;
    private javax.swing.JButton btnSvepsTangerina;
    private javax.swing.JButton btnToplaCokolada;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlPodaciOProizvodu;
    private javax.swing.JPanel pnlSviProizvodi;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtStanje;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables
}
