/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package debtcontrol.form;

import debtcontrol.form.controller.KlubController;

/**
 *
 * @author podrska
 */
public class KlubForm extends javax.swing.JFrame {

    /**
     * Creates new form KlubForm
     */
    public KlubForm() {
        initComponents();
        setLocationRelativeTo(null);
     //   setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOtvoriRacun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemDodajKorisnika = new javax.swing.JMenuItem();
        menuItemListaKorisnika = new javax.swing.JMenuItem();
        menuProizvodi = new javax.swing.JMenu();
        itemDodajProizvod = new javax.swing.JMenuItem();
        menuItemListaProizvoda = new javax.swing.JMenuItem();
        menuIzvestaji = new javax.swing.JMenu();
        menuItemIzvestajiKorisnik = new javax.swing.JMenuItem();
        menuItemIzvestajProizvodi = new javax.swing.JMenuItem();
        menuItemIzvestajiRacuni = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DEBT CONTROL");
        setBackground(new java.awt.Color(204, 255, 204));
        setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        getContentPane().setLayout(null);

        btnOtvoriRacun.setBackground(new java.awt.Color(153, 204, 255));
        btnOtvoriRacun.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        btnOtvoriRacun.setText("OTVORI   RAČUN");
        btnOtvoriRacun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOtvoriRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtvoriRacunActionPerformed(evt);
            }
        });
        getContentPane().add(btnOtvoriRacun);
        btnOtvoriRacun.setBounds(830, 350, 370, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\podrska\\Desktop\\SLIKE ZA APP\\coca cola.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1520, 250, 400, 130);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\podrska\\Desktop\\SLIKE ZA APP\\schweppes.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 720, 300, 170);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\podrska\\Desktop\\SLIKE ZA APP\\png-transparent-fanta-fizzy-drinks-orange-soft-drink-coca-cola-logo-fanta-text-orange-logo-thumbnail.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 360, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\podrska\\Desktop\\SLIKE ZA APP\\rosa_logo.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 470, 280, 160);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\podrska\\Desktop\\SLIKE ZA APP\\knjaz_milos.gif")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1670, 520, 200, 150);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\podrska\\Desktop\\SLIKE ZA APP\\next 1.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1540, 790, 180, 120);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\podrska\\Desktop\\SLIKE ZA APP\\fon logo.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(850, 760, 340, 170);

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Wide Latin", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>  <div style=' text-align: center;'>DEBT    <br>   CONTROL </div> </html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(740, 20, 510, 150);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 150, 1950, 10);

        jMenu1.setText("KORISNIK");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MenuItemDodajKorisnika.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuItemDodajKorisnika.setText("Dodaj korisnika");
        MenuItemDodajKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDodajKorisnikaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemDodajKorisnika);

        menuItemListaKorisnika.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemListaKorisnika.setText("LIsta korisnika");
        menuItemListaKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListaKorisnikaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemListaKorisnika);

        jMenuBar1.add(jMenu1);

        menuProizvodi.setText("PROIZVOD");
        menuProizvodi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        itemDodajProizvod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemDodajProizvod.setText("Dodaj proizvod");
        itemDodajProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDodajProizvodActionPerformed(evt);
            }
        });
        menuProizvodi.add(itemDodajProizvod);

        menuItemListaProizvoda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemListaProizvoda.setText("Lista proizvoda");
        menuItemListaProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListaProizvodaActionPerformed(evt);
            }
        });
        menuProizvodi.add(menuItemListaProizvoda);

        jMenuBar1.add(menuProizvodi);

        menuIzvestaji.setText("IZVEŠTAJ");
        menuIzvestaji.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuItemIzvestajiKorisnik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemIzvestajiKorisnik.setText("Za Korisnike");
        menuItemIzvestajiKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIzvestajiKorisnikActionPerformed(evt);
            }
        });
        menuIzvestaji.add(menuItemIzvestajiKorisnik);

        menuItemIzvestajProizvodi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemIzvestajProizvodi.setText("Za Proizvode");
        menuItemIzvestajProizvodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIzvestajProizvodiActionPerformed(evt);
            }
        });
        menuIzvestaji.add(menuItemIzvestajProizvodi);

        menuItemIzvestajiRacuni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuItemIzvestajiRacuni.setText("Za Racune");
        menuItemIzvestajiRacuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIzvestajiRacuniActionPerformed(evt);
            }
        });
        menuIzvestaji.add(menuItemIzvestajiRacuni);

        jMenuBar1.add(menuIzvestaji);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDodajProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDodajProizvodActionPerformed
//        DodajProizvodForm proizvodForm = new DodajProizvodForm(null, true);
//        proizvodForm.setVisible(true);
            KlubController.dodajProizvodForm();
    }//GEN-LAST:event_itemDodajProizvodActionPerformed

    private void btnOtvoriRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtvoriRacunActionPerformed
//        RacunForm racunForm = new RacunForm(null, true);
//        racunForm.setVisible(true);
        KlubController.dodajRacunForm();

    }//GEN-LAST:event_btnOtvoriRacunActionPerformed

    private void MenuItemDodajKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDodajKorisnikaActionPerformed
//        DodajKorisnikaForm dzf = new DodajKorisnikaForm(this, true);
//        dzf.setVisible(true);
          KlubController.dodajKorinikaForm();

    }//GEN-LAST:event_MenuItemDodajKorisnikaActionPerformed

    private void menuItemListaKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListaKorisnikaActionPerformed
//        ListaKorisnikaForm lzf = new ListaKorisnikaForm(null, true);
//        lzf.setVisible(true);
              KlubController.dodajListuKorisnikaForm();

    }//GEN-LAST:event_menuItemListaKorisnikaActionPerformed

    private void menuItemIzvestajiRacuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIzvestajiRacuniActionPerformed
//        IzvestajRacunaForm irf = new IzvestajRacunaForm(null, true);
//        irf.setVisible(true);

              KlubController.dodajIzvestajRacunaForm();

    }//GEN-LAST:event_menuItemIzvestajiRacuniActionPerformed

    private void menuItemIzvestajiKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIzvestajiKorisnikActionPerformed
//        IzvestajKorisnikaForm ikf = new IzvestajKorisnikaForm(null, true);
//        ikf.setVisible(true);
              KlubController.dodajIzvestajKorisnikaForm();

    }//GEN-LAST:event_menuItemIzvestajiKorisnikActionPerformed

    private void menuItemListaProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListaProizvodaActionPerformed
//        ListaProizvodaForm lpf = new ListaProizvodaForm(this, true);
//        lpf.setVisible(true);
          KlubController.dodajListuProizvodaForm();
    }//GEN-LAST:event_menuItemListaProizvodaActionPerformed

    private void menuItemIzvestajProizvodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIzvestajProizvodiActionPerformed
//        IzvestajProizvodaForm ipf = new IzvestajProizvodaForm(this, true);
//        ipf.setVisible(true);

          KlubController.dodajIzvestajProizvodaForm();

    }//GEN-LAST:event_menuItemIzvestajProizvodiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemDodajKorisnika;
    private javax.swing.JButton btnOtvoriRacun;
    private javax.swing.JMenuItem itemDodajProizvod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem menuItemIzvestajProizvodi;
    private javax.swing.JMenuItem menuItemIzvestajiKorisnik;
    private javax.swing.JMenuItem menuItemIzvestajiRacuni;
    private javax.swing.JMenuItem menuItemListaKorisnika;
    private javax.swing.JMenuItem menuItemListaProizvoda;
    private javax.swing.JMenu menuIzvestaji;
    private javax.swing.JMenu menuProizvodi;
    // End of variables declaration//GEN-END:variables
}
